name: integrated-${APP_NAME}-prod

services:
  nginx-staticweb:
    build:
      context: .
      dockerfile: nginx/Dockerfile.prod
      additional_contexts:
        web_ui_source: "${WEB_UI_SOURCE_PATH:-../react-web-ui}"
      args:
        NGINX_CONFIG: default.prod.conf
    image: nginx-staticweb:${APP_NAME}-integrated-prod
    container_name: nginx-staticweb-${APP_NAME}
    ports:
      - "${NGINX_BIND_ADDRESS:-127.0.0.1}:${NGINX_PORT:-8080}:80"
    depends_on:
      - tomcat-frontend
    restart: unless-stopped
    networks:
      - web-network

  tomcat-frontend:
    build:
      context: .
      dockerfile: tomcat/Dockerfile
      additional_contexts:
        frontwas_source: "${FRONTEND_SOURCE_PATH:-../frontend}"
    image: tomcat-frontend:${APP_NAME}
    container_name: tomcat-frontend-${APP_NAME}
    expose:
      - "8080"
    restart: unless-stopped
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
