name: staticweb-${APP_NAME}-prod

services:
  nginx-staticweb:
    build:
      context: .
      dockerfile: nginx/Dockerfile.prod
      additional_contexts:
        web_ui_source: "${WEB_UI_SOURCE_PATH:-../react-web-ui}"
      args:
        NGINX_CONFIG: default.staticweb.prod.conf
    image: nginx-staticweb:${APP_NAME}-staticweb-prod
    container_name: nginx-staticweb-${APP_NAME}
    ports:
      - "${NGINX_BIND_ADDRESS:-127.0.0.1}:${NGINX_PORT:-8080}:80"
    restart: unless-stopped
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
