FROM node:24.20.0-bookworm

WORKDIR /app

COPY web-ui/package.json web-ui/package-lock.json ./
RUN npm ci

COPY web-ui/ ./

EXPOSE 8183

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "8183"]
